name: Continous Integration

on:
  push:
    branches: 
      - main

  workflow_dispatch:
  
env: 
  DOTNET_VERSION: '6.0.x'
  AZURE_WEBAPP_NAME: test-github-action-workflow
    
jobs:
  build:
    runs-on: windows-latest
    steps: 
      - name: checkout the code
        uses: actions/checkout@v2

      - name: setup dotnet 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: restore
        run: dotnet restore

      - name: build app
        run: dotnet build -c Release --no-restore

      - name: publish app
        run: dotnet publish -c Release -o ./publish

      - name: Deploy the app
        uses: azure/webapp-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}                                                                                                                                                                                       `` }}
          publish-profile: ${{ secret.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

